apiVersion: v1
kind: Service
metadata:
  name: jenkinsminikube-service
spec:
  type: NodePort
  selector:
    app: jenkinsminikube-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007